[package]
name = "systemd-manager"
version = "0.4.2"
license = "GPL-3.0"
repository = "https://github.com/mmstick/systemd-manager"
readme = "README.md"
authors = ["Michael Murphy <mmstickman@gmail.com>"]
documentation = "A GTK3 GUI for managing systemd services on Linux"
keywords = [ "gtk", "linux", "systemd" ]

[dependencies]
dbus = "0.9.7"
gtk = { version = "0.8.2", package = "gtk4", features = ["v4_12"] }
