[package]
name = "sysd-manager"
version = "1.3.2"
edition = '2021'
license = "GPL-3.0-or-later"
repository = "https://github.com/plrigaux/sysd-manager"
readme = "README.md"
authors = ["Pierre-Luc Rigaux <plrigaux@gmail.com>"]
description = "A GUI to manage systemd units"
keywords = ["gtk4", "linux", "systemd"]
rust-version = "1.80"
build = "build.rs"
include = [
    "build.rs",
    "/src",
    "LICENCE",
    "README.md",
    "/data",
    "!/**/meson.build",
]
default-run = "sysd-manager"

[[bin]]
name = "sysd-manager"
path = "src/main.rs"

[[bin]]
name = "force-build"
path = "build.rs"

[profile.release]
lto = true

[dependencies]
gtk = { version = "0.9", package = "gtk4", features = ["v4_16"] }
adw = { version = "0.7", package = "libadwaita", features = ["v1_6"] }
log = "0.4"
libc = "0.2"
env_logger = "0.11.3"
dotenv = "0.15.0"
strum = { version = "0.26", features = ["derive"] }
tokio = { version = "1.41", features = ["full"] }
zbus = "5"
zvariant = "5"
serde = "1.0"
chrono = "0.4.38"
regex = "1.11.0"

[dev-dependencies]

[build-dependencies]
#glib-build-tools = "0.19.0"
#cargo-generate-rpm = "0.14.1"


[package.metadata.generate-rpm]
summary = "A systemd units manager"
assets = [
    { source = "target/release/sysd-manager", dest = "/usr/bin/sysd-manager", mode = "755" },
    { source = "data/applications/io.github.plrigaux.sysd-manager.desktop", dest = "/usr/share/applications/io.github.plrigaux.sysd-manager.desktop", mode = "644" },
    { source = "data/icons/hicolor/scalable/apps/io.github.plrigaux.sysd-manager.svg", dest = "/usr/share/icons/hicolor/scalable/apps/io.github.plrigaux.sysd-manager.svg", mode = "644" },
    { source = "data/schemas/io.github.plrigaux.sysd-manager.gschema.xml", dest = "/usr/share/glib-2.0/schemas/io.github.plrigaux.sysd-manager.gschema.xml", mode = "644" },
]

[package.metadata.generate-rpm.requires]
coreutils = ">= 9"
polkit = ">= 123"
systemd = ">= 254"
