[package]
name = "sysd-manager"
version = "0.0.1"
edition = '2021'
license = "GPL-3.0"
repository = "https://github.com/mmstick/systemd-manager"
readme = "README.md"
authors = ["Pierre-Luc Rigaux <plrigaux@gmail.com>"]
documentation = "A GTK4 GUI for managing systemd unit"
keywords = [ "gtk4", "linux", "systemd" ]
rust-version = "1.79"


[dependencies]
dbus = "0.9.7"
gtk = { version = "0.8.2", package = "gtk4", features = ["v4_12"] }
log = "0.4"
libc = "0.2"
env_logger = "0.11.3"
dotenv = "0.15.0"

