[package]
name = "tiny_daemon"
version = "0.1.6"
edition = '2021'
license = "GPL-3.0-or-later"
repository = "https://github.com/plrigaux/sysd-manager"
readme = "README.md"
authors = ["Pierre-Luc Rigaux <plrigaux@gmail.com>"]
description = "A Test service"
keywords = ["linux", "systemd"]
rust-version = "1.80"


[dependencies]
log = "0.4"
env_logger = "0.11"
clap = { version = "4.5", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
signal-hook = "0.3.17"
anstyle = "1"
axum = "0.8"
libc = "0.2"
