[package]
name = "translating"
version = "0.0.0"
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
description = "Tools to use "
keywords = ["xtext"]
license = { workspace = true }

